### ISSUE TITLE
feat: GitHub Pages Deployment

### ISSUE THREAD

**Issue by krishdevdb** [Skyhero-admin/Sky8-emu.js#1]
This repository looks like a static website, how about deploying to [GitHub Pages](https://github.io)

More info/help on the topic: [GitHub Documentation](https://docs.github.com/en/pages)

**Comment by Skyhero-admin** [comment]
oh thanks

**Comment by Skyhero-admin** [comment]
I was just wondering about why it wasn't being deployed properly
I am planning on deploying it properly once I fix the bugs on this one

**Comment by krishdevdb** [comment]
@Skyhero-admin you should deploy the thing from the first version, cause bugs are not bug they are the demand for developers! People will only contribute if they know what they are contributing to!

**Comment by Skyhero-admin** [comment]
ohk cool
Thanks for the suggestion

**Comment by krishdevdb** [comment]
Seems you fixed this issue! Now lets move on to issue #2
