### ISSUE TITLE
feat: Add a link to deployed version in github setting

### ISSUE THREAD

**Issue by krishdevdb** [Skyhero-admin/Sky8-emu.js#2]
![screen-capture (1)](https://user-images.githubusercontent.com/76587897/120878954-884b1b80-c5dd-11eb-9c76-911de7814bbf.gif)

Link: https://skyhero-admin.github.io/Sky8-emu.js

**Comment by Skyhero-admin** [comment]
Cool 
thanks for the gif explanation as well😄

**Comment by krishdevdb** [comment]
Great seems this is fixed too now let's move on to #3 Make sure to create a branch for the edits and create a pull request
