### ISSUE TITLE
feat: Setup Eslint

### ISSUE THREAD

**Issue by krishdevdb** [Skyhero-admin/Sky8-emu.js#3]
Eslint is a code formatted and style checker, it allows you to lint your code and fix it, most JavaScript projects use it, it is used with node.js with little to no setup I recommend using eslint config standard. 

```bash
node -v
npm i eslint
npx eslint --init
```

More info at [eslint.org](https://eslint.org/)

**Comment by Skyhero-admin** [comment]
How does it look for errors

**Comment by Skyhero-admin** [comment]
I installed it
But how do I test if it is working 
🤔

**Comment by krishdevdb** [comment]
@Skyhero-admin you can use `npx eslint .` it will test your code, with the code style, you can use `npx eslint --fix` to fix the issues + use editor specific plugins: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

**Comment by krishdevdb** [comment]
Looks like you're done with ESLint, now move to #4
